server:
  port: 8091
  tomcat:
    accesslog:
      enabled: true
      file-date-format: .yyyy-MM-dd
      pattern: '%h %l %u [%{yy-MM-dd:HH:mm:ss}t] "%r" %s %b %D %{User-Agent}i'
      rename-on-rotate: true

  error:
    whitelabel:
      enabled: false

spring:
  datasource:
    url: ENC(/NqesvJNUZWjE4AwadpTzF7DneGem8Up1F+sdj+vg3qS/VEwBq+OHgzKsFeCcJQ9oVsjbave4U4=)
    driver-class-name: org.postgresql.Driver
    username: ENC(7nwsurvoUPBzbhJnaPjgIIQ0mwpoOg39)
    password: ENC(7nwsurvoUPBzbhJnaPjgIIQ0mwpoOg39)



logging:
  level:
    root: info
    com.ddimtech.sbproject: debug

springdoc:
  swagger-ui:
    path: /docs
    tags-sorter: alpha
    operations-sorter: method

sbproject:
  jwt-secret: ENC(HYLzRM8mENqzHEIg8cGCJAn1KF7lIenAEFcl0gCAP7peRLOKtbAZCHBDBMND9lU4DCFmPu7aoEpdNNisjUcktWmFrM112tohfeK8YIetumrF1fFJgTR2+g==)

